ALTER SEQUENCE group_id_seq RESTART WITH 1;
INSERT INTO "group" ( group_name, group_info) VALUES ( 'Purpose', 'Focus and align travel to core business objectives, by ensuring the right trips happen and they lead to success.');
INSERT INTO "group" ( group_name, group_info) VALUES ( 'Booking/TMC', 'Share with travelers where they should be making their bookings that lead to the best prices and experiences.');
INSERT INTO "group" ( group_name, group_info) VALUES ( 'Payment', 'How should travel be purchased, and when or if personal cards can be used.');
INSERT INTO "group" ( group_name, group_info) VALUES ( 'Types of travel', 'Each trip is different, and therefore there should be different considerations for different trip types.');
INSERT INTO "group" ( group_name, group_info) VALUES ( 'Inconvenient Travel', 'Are considerations given to employees who travel at inconvenient times such as weekend or public holidays');
INSERT INTO "group" ( group_name, group_info) VALUES ( 'Loyalty Programs', 'Can employees earn loyalty points earned for corporate travel');
INSERT INTO "group" ( group_name, group_info) VALUES ( 'Air', 'When can travelers book different cabins, advice on which airlines to use, and when to buy');
INSERT INTO "group" ( group_name, group_info) VALUES ( 'Hotel', 'When can travelers book upgraded rooms, advice on which hotels to use, when to buy and Airbnb');
INSERT INTO "group" ( group_name, group_info) VALUES ( 'Rail', 'When can travelers book different cabins, express or regional, and when to buy');
INSERT INTO "group" ( group_name, group_info) VALUES ( 'Car Rental', 'When can travelers book upgraded cars, advice on which car rental companies to use, and insurance');
INSERT INTO "group" ( group_name, group_info) VALUES ( 'Ground', 'Using taxis, limousines, Uber and Lyft, and using your own personal car');
INSERT INTO "group" ( group_name, group_info) VALUES ( 'Leisure + Vacation', '60% of business trips now include an element of leisure. Share what discounts can be used, and what elements of a trip can be expensed.');
INSERT INTO "group" ( group_name, group_info) VALUES ( 'Sustainability', 'When is it better to fly, go by rail, or to drive, and offsetting carbon emisions.');
INSERT INTO "group" ( group_name, group_info) VALUES ( 'Visas + Passports', 'US nationals require visas when traveling to over 70 countries. Information on how to get a foreign country visa, passports, and expedited fees.');
INSERT INTO "group" ( group_name, group_info) VALUES ( 'Per diems + expenses', 'Share with travelers how much money they can spend when on a trip on meals, tips, and other potential expenses.');
INSERT INTO "group" ( group_name, group_info) VALUES ( 'Gifts', 'Information on what can and cannot be given as corporate gifts.');
INSERT INTO "group" ( group_name, group_info) VALUES ( 'Reshop', 'If utilizing reshopping tools, inform the traveler they are in operation.');
INSERT INTO "group" ( group_name, group_info) VALUES ( 'Admin', 'Ensure travelers are kept up to date on changes to the policy, and who to reach in case of emergency.');