ALTER SEQUENCE question_id_seq RESTART WITH 1;
INSERT INTO  question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Reason for travel policy document',true,true,true,true,true);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Purposeful - virtual alternative?',true,true,true,true,true);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Scope',true,true,true,true,true);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Reason for trips / reason codes',true,true,true,true,true);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('One trip leading into next',true,true,true,true,true);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Where to book',true,true,true,true,true);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Online vs offline',false,true,false,false,false);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Single itinerary/PNR',false,true,false,false,false);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Rebooking',true,true,false,false,true);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Cancellations',true,true,false,false,true);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Tax implications of time out of state/country',true,true,true,false,true);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Pre Trip Approvals',true,true,true,false,true);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Corporate card usage',true,true,true,false,true);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Personal card usage',true,true,true,false,true);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('BTA, virtual cards',true,true,true,false,true);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Reconcilliation time',false,true,true,false,true);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Transient',true,true,true,true,false);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Interviews',true,true,true,true,false);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Internship Travel',true,true,true,true,false);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('MICE / Meetings',true,true,true,true,false);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Group Travel',true,true,true,true,false);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Team Building',true,true,true,true,false);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Entertainment',true,true,true,true,false);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Award + Recognition',true,true,true,true,false);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Trips home on extended projects',true,true,true,false,false);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Partner/family travel on extended projects',true,true,true,false,false);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Last minute travel - Spouse/Partner/Dependent care',true,true,true,false,false);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Worked Late',true,true,true,false,false);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Worked on holiday',true,true,true,false,false);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Worked on weekend',true,true,true,false,false);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Point collection',false,true,true,false,false);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Advanced purchase',false,true,false,false,false);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Preferred Supplier',true,true,true,false,false);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Baggage',false,true,false,false,false);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('cabin policy (distance/time/hierarchy/RW)',true,true,true,false,false);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Upgrades',true,true,true,false,false);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Seat selection',true,true,true,false,false);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Medical exceptions',true,true,true,false,false);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Red Eye flights',true,true,true,false,false);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Overnight exception (straight into office)',true,true,true,false,false);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Aircraft type',true,false,false,false,false);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('# of employees',true,false,false,false,true);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Lowest logical',false,true,false,false,false);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Direct vs Indirect',true,true,true,true,false);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Route cap',false,true,false,false,false);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Customer/client travel',false,true,true,false,false);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Advanced purchase',false,true,false,false,false);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Preferred Supplier',true,true,true,false,false);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Room type/category',false,true,true,false,false);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Extended stay (> 7 days)',false,true,true,false,false);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Motels / 2 door policy',false,true,true,false,false);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Airbnb & shared accommodations',true,true,true,false,false);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Lowest logical',false,true,false,false,false);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('City cap',false,true,false,false,false);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Double occupancy',false,true,true,false,false);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Tips',false,true,true,false,false);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Advanced purchase',false,true,false,false,false);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Express vs Regional',false,true,true,false,false);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('cabin policy (distance/time/hierarchy/RW)',true,true,true,false,false);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Preferred Supplier',true,true,true,false,false);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Insurance',true,true,false,false,true);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Car tier',true,true,true,false,false);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Incidentals',false,true,false,false,false);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Fuel - self refill',false,true,false,false,false);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Fuel - rental refill',false,true,false,false,false);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Parking',false,true,false,false,false);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Lowest logical',false,true,false,false,false);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Market cap',false,true,false,false,false);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Tolls',false,true,false,false,false);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Taxi',true,true,true,false,false);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Uber/Lyft/Market alternative',true,true,true,false,false);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Limosuine',true,true,true,false,false);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Public transport',true,true,true,false,false);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Tips',false,true,true,false,false);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Own car - insurance req',true,true,true,false,false);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Own car - mileage reimbursement',true,true,true,false,false);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Parking',true,true,true,false,false);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Valet Parking',true,true,true,false,false);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Extended trip ''Bleisure'' deals',true,true,true,false,true);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Pure leisure trip use of corp deals',false,false,true,false,true);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Air vs Rail',false,true,true,true,false);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Air vs Driving',false,true,true,true,false);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Offsetting',false,true,false,true,false);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Applicabiity',true,true,true,false,true);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Preferred Supplier',true,true,true,false,true);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Passport application fee',true,true,true,false,true);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Expedited fees',true,true,true,false,true);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Food and Beverage',false,true,true,false,true);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Tips',false,true,true,false,true);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Alcohol',true,true,true,false,true);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Dry cleaning',false,true,true,true,true);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Entertainment (in room movies)',false,true,true,true,true);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Gym',false,true,true,false,true);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Roaming / Mobile phone reimbursement',false,true,true,false,true);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Lost/delayed luggage',false,true,true,false,true);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Giving Corporate gifts',false,true,true,false,true);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Receiving Corporate gifts',false,true,true,false,true);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Inform travelers of reshop tools',false,true,true,false,false);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('Contact details',true,true,true,true,true);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('One pager for key facts',true,true,true,true,true);
INSERT INTO question (question_text,safety,cost,experience,sustainability,business_processes) VALUES  ('History of changes',false,false,true,false,true);
